### ISSUE TITLE
Getting crash java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState

### ISSUE THREAD

**Issue by MiselMojzes** [guardian/toolargetool#22]
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2750)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2811)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6316)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
        at com.gu.toolargetool.ActivitySavedStateLogger.onActivityCreated(ActivitySavedStateLogger.kt)
        at android.app.Application.dispatchActivityCreated(Application.java:197)

**Comment by mjdenham** [comment]
There is a missing ? after Bundle in ActivitySavedStateLogger.  The signature should be:
`override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?)`

**Comment by AlphaGao1993** [comment]
still meeting this problem, have you build new release version ?

**Comment by hovterteryan** [comment]
When will update release version? Same problem on toolargetool:0.2.0@aar

**Comment by nvasilev0101** [comment]
If you need to use the tool asap and can't wait for a new release just download the repo locally and use the library from your local file directory.

**Comment by brookhong** [comment]
Same problem on toolargetool:0.2.0@aar

**Comment by paul1992li** [comment]
please update release version and update github release note. 
![image](https://user-images.githubusercontent.com/12912067/57189199-07248480-6f3e-11e9-9c53-663f0ddcecd5.png)

**Comment by maxspencer** [comment]
Sorry for this has gone unresolved for so long, I think it should be resolved in the latest version which is `0.2.1`.

**Comment by businessworksolution** [comment]
Not solved in new library also.

 java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter folderName
        at com.esafirm.imagepicker.model.Folder.<init>(Unknown Source:2)
        at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.run(DefaultImageFileLoader.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
