### ISSUE TITLE
集成时，报错崩溃

### ISSUE THREAD

**Issue by JasonMiss** [guardian/toolargetool#28]
在Application中初始化以下代码时，直接报以下错误崩溃
TooLargeTool.startLogging(this);

log崩溃日志：

Process: com.nacai.bocai, PID: 20013
                                                                 java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/fragment/app/FragmentManager$FragmentLifecycleCallbacks;
                                                                     at com.gu.toolargetool.TooLargeTool.startLogging(TooLargeTool.kt:96)
                                                                     at com.gu.toolargetool.TooLargeTool.startLogging(TooLargeTool.kt:90)
                                                                     at com.gu.toolargetool.TooLargeTool.startLogging$default(TooLargeTool.kt:89)
                                                                     at com.gu.toolargetool.TooLargeTool.startLogging(Unknown Source:3)

**Comment by yilylong** [comment]
同问

**Comment by yilylong** [comment]
看样子要用到Androidx下面的FragmentManager 可是我工程没有引用androidx相关的支持包

**Comment by waynett** [comment]
同问

**Comment by amed901107** [comment]
Same question?

**Comment by songlin0859** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/fragment/app/FragmentManager$FragmentLifecycleCallbacks;
