### ISSUE TITLE
App crashes while calling startLogging

### ISSUE THREAD

**Issue by desgraci** [guardian/toolargetool#5]
sdk 25, google pixel

`Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.FragmentManager$FragmentLifecycleCallbacks" on path: DexPathList[[zip file "/data/app/com.testapp.dev-1/base.apk"],nativeLibraryDirectories=[/data/app/com.testapp.dev-1/lib/arm64, /system/lib64, /vendor/lib64]]
04-19 12:35:07.060 20080-20080/? I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
04-19 12:35:07.060 20080-20080/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
04-19 12:35:07.061 20080-20080/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
04-19 12:35:07.061 20080-20080/? I/art:     at void com.gu.toolargetool.TooLargeTool.startLogging(android.app.Application, int, java.lang.String) (TooLargeTool.java:155)
04-19 12:35:07.061 20080-20080/? I/art:     at void com.gu.toolargetool.TooLargeTool.startLogging(android.app.Application) (TooLargeTool.java:144)
04-19 12:35:07.061 20080-20080/? I/art:     at void com.testapp.app.App.onCreate() (App.java:51)
04-19 12:35:07.061 20080-20080/? I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1024)
04-19 12:35:07.061 20080-20080/? I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5405)
04-19 12:35:07.061 20080-20080/? I/art:     at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
04-19 12:35:07.061 20080-20080/? I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1546)
04-19 12:35:07.061 20080-20080/? I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
04-19 12:35:07.061 20080-20080/? I/art:     at void android.os.Looper.loop() (Looper.java:154)
04-19 12:35:07.061 20080-20080/? I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6121)
04-19 12:35:07.061 20080-20080/? I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
04-19 12:35:07.061 20080-20080/? I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
04-19 12:35:07.061 20080-20080/? I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
04-19 12:35:07.061 20080-20080/? D/AndroidRuntime: Shutting down VM
04-19 12:35:07.061 20080-20080/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.testapp.dev, PID: 20080
                                                   java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentManager$FragmentLifecycleCallbacks;
                                                       at com.gu.toolargetool.TooLargeTool.startLogging(TooLargeTool.java:155)
                                                       at com.gu.toolargetool.TooLargeTool.startLogging(TooLargeTool.java:144)
                                                       at com.testapp.app.App.onCreate(App.java:51)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5405)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.FragmentManager$FragmentLifecycleCallbacks" on path: DexPathList[[zip file "/data/app/com.testapp.dev-1/base.apk"],nativeLibraryDirectories=[/data/app/com.testapp.dev-1/lib/arm64, /system/lib64, /vendor/lib64]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at com.gu.toolargetool.TooLargeTool.startLogging(TooLargeTool.java:155) 
                                                       at com.gu.toolargetool.TooLargeTool.startLogging(TooLargeTool.java:144) 
                                                       at com.testapp.app.App.onCreate(App.java:51) 
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5405) 
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
`

**Comment by ghiyats-olx** [comment]
have you found any solution for this?

**Comment by corcoran** [comment]
You need to be running version >=25.1.0 of support lib

**Comment by joshuapinter** [comment]
I'm getting the same error. Is this tool still supported, @maxspencer ?

Latest commit was Feb 20, 2019, so it appears so but doesn't appear to be much support on how to get things working on current installs.

**Comment by JmStefanAndroid** [comment]
the same error on v0.2.1
